version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  apt_packages:
    - cmake
    - build-essential
  jobs:
    pre_install:
      - bash devtools/scripts/rtd_pre_install.sh

conda:
    environment: docs/environment.yaml

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: build/python
