version: 2

conda:
    file: devtools/conda-envs/rtd_env.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - bash devtools/scripts/rtd_pre_build.sh

python:
  version: "3.10"
  install:
    - method: pip
      path: build/python
