#!/bin/bash
cmake \
-DOPENMM_DIR=${CONDA_PREFIX} \
-DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
-DNATIVENONBONDED_BUILD_CUDA_LIB=ON \
-DNATIVENONBONDED_BUILD_OPENCL_LIB=ON \
..
