name: Linux

# Temporarily disabled - uses OpenMM 8.1
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "main"

jobs:
  unix:
    runs-on: ubuntu-22.04
    name: Linux (Python ${{ matrix.python-version }}, OpenMM ${{ matrix.openmm-version }}, GCC ${{ matrix.compiler-version }}, CUDA ${{ matrix.cuda-version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
            openmm-version: "8.1"
            cuda-version: "11.8.0"
            compiler-version: "11.4"

    steps:
      - name: "Check out"
        uses: actions/checkout@v5

      - name: "Install CUDA Toolkit"
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
          method: 'network'

      - name: "Install AMD OpenCL"
        run: source devtools/scripts/install_amd_opencl.sh

      - name: "Update the conda enviroment file"
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '@'
          tokenSuffix: '@'
          files: devtools/conda-envs/build-cudatoolkit-11.8.yml
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          COMPILER_VERSION: ${{ matrix.compiler-version }}
          OPENMM_VERSION: ${{ matrix.openmm-version }}

      - uses: conda-incubator/setup-miniconda@v3
        name: "Install dependencies with conda"
        with:
          activate-environment: build
          environment-file: devtools/conda-envs/build-cudatoolkit-11.8.yml
          python-version: ${{ matrix.python-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: conda list

      - name: "Configure"
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake ..

      - name: "Build"
        shell: bash -l {0}
        run: |
          cd build
          make -j2 install
          make -j2 PythonInstall

      - name: "List plugins"
        shell: bash -l {0}
        run: |
          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"

      - name: "Run C++ test"
        shell: bash -l {0}
        run: |
          cd build
          ctest --output-on-failure --exclude-regex 'Test[Cuda|OpenCL]'

      - name: "Run Python test"
        shell: bash -l {0}
        run: |
          cd build/python/tests
          pytest --verbose -k 'not (Cuda or OpenCL)' Test*
