name: MacOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    name: MacOS (Python ${{ matrix.python-version }}, OpenMM ${{ matrix.openmm-version }}, Clang ${{ matrix.compiler-version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            cuda-version: ""
            compiler-version: "19.1"
            python-version: "3.12"
            openmm-version: "8.3"

    steps:
      - name: "Check out"
        uses: actions/checkout@v5

      - name: "Install SDK on MacOS"
        run: source devtools/scripts/install_macos_sdk.sh

      - name: "Update the conda enviroment file"
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '@'
          tokenSuffix: '@'
          files: devtools/conda-envs/build-${{ matrix.os }}.yml
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          COMPILER_VERSION: ${{ matrix.compiler-version }}
          OPENMM_VERSION: ${{ matrix.openmm-version }}

      - uses: conda-incubator/setup-miniconda@v3
        name: "Install dependencies with conda"
        with:
          activate-environment: build
          environment-file: devtools/conda-envs/build-${{ matrix.os }}.yml
          python-version: ${{ matrix.python-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: conda list

      - name: "Configure"
        shell: bash -l {0}
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DPLUGIN_BUILD_CUDA_LIB=OFF

      - name: "Build"
        shell: bash -l {0}
        env:
          CC: clang
          CXX: clang++
        run: |
          cd build
          make -j2 install
          make -j2 PythonInstall

      - name: "List plugins"
        shell: bash -l {0}
        run: |
          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"

      - name: "Run C++ test"
        shell: bash -l {0}
        run: |
          cd build
          ctest --output-on-failure --exclude-regex 'Test[Cuda|OpenCL]'

      - name: "Run Python test"
        shell: bash -l {0}
        run: |
          cd build/python/tests
          pytest --verbose -k 'not (Cuda or OpenCL)' Test*